apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-5
  namespace: sock-shop-nr
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: front-end-5
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: front-end-5
    spec:
      containers:
      - env:
        - name: SESSION_REDIS
          value: "true"
        - name: NEW_RELIC_APP_NAME
          value: k8s_front_end-5
        - name: NEW_RELIC_LICENSE_KEY
          value: eeb7295ea271868ac1048f0bb4e38cf0FFFFNRAL
        - name: NEW_RELIC_LOG
          value: stdout
        - name: NEW_RELIC_DISTRIBUTED_TRACING_ENABLED
          value: "true"
        - name: NEW_RELIC_INFINITE_TRACING_TRACE_OBSERVER_HOST
          value: 448bdf21-6ae0-48d8-a693-fd11b898ae22.aws-us-west-2.tracing.edge.nr-data.net
        image: azumax/front-end-5:test
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8079
            scheme: HTTP
          initialDelaySeconds: 300
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
        name: front-end-5
        ports:
        - containerPort: 8079
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8079
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 300m
            memory: 1000Mi
          requests:
            cpu: 300m
            memory: 1000Mi
        securityContext:
          capabilities:
            drop:
            - all
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 10001
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      nodeSelector:
        beta.kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
